modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="malisiscore"
version="${file.jarVersion}"
displayName="Malisis Core"
credits="Ordinastie and PaleoCrafter for the original mod"
authors="OneLousyDev"
description='''A unofficial port of Malisis Core to modern Minecraft versions'''
[[dependencies.malisiscore]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.malisiscore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

